- name: install jenkins

tasks:
          - name: Add Jenkins repository to yum for yum to know the install source
            command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo

          - name: Add Jenkins GPG to authorized key so that Jenkins can be installed
            rpm_key:
                     key: https://pkg.jenkins.io/redhat/jenkins.io.key
                     state: present

          - name: install Jenkins
            package:
                    name: "{{ item }}"
                    state: latest
            with_items:
                    - jenkins

          - name: start Jenkins service
            service:
                    name: jenkins
                    state: started
